name: macos_dock_progress
description: "An API wrapper of DockProgress for Flutter, make you able to interacting with macOS dock icon progress bars in Flutter."
version: 1.1.0
homepage: https://github.com/NightFeather0615/macos_dock_progress

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: MacosDockProgressPlugin
